### ISSUE TITLE
about page help

### ISSUE THREAD

**Issue by toma0090** [toma0090/portfolio#1]
@abhaysharma
Hello,
in. my about page my skills and the picture has to be look like this but mine 
<img width="432" alt="Screenshot 2023-12-12 at 12 29 46 AM" 
src="https://github.com/toma0090/portfolio/assets/133021520/70a8a5d2-4180-4e31-917a-41dc8b738d5f">

<img width="1063" alt="Screenshot 2023-12-12 at 12 41 02 AM" src="https://github.com/toma0090/portfolio/assets/133021520/7e9128ec-ee3a-408d-b3b3-03dd0a395c56">
 but my mine look like this can you help me the skills boxes and the photo position

**Comment by abhaysharma** [comment]
@toma0090 please push your code to GitHub so I can investigate.

**Comment by toma0090** [comment]
@abhaysharma I pushed it already

**Comment by abhaysharma** [comment]
@toma0090 please close the issue if it is done. Thanks!
